# 2025-05-20 mikey: pursuant to https://wiki.archlinux.org/title/PipeWire
pulse.cmd = [
  { cmd = "load-module" args = "module-zeroconf-discover" }
  { cmd = "load-module" args = "module-zeroconf-publish" }
]
